export default {
  id: 26,
  brandId: 3,
  productCategoryId: 19,
  feightTemplateId: 0,
  productAttributeCategoryId: 3,
  name: '华为 HUAWEI P20 ',
  pic: 'http://127.0.0.1:9090/assets/home/goodscard/img-huawei-phone.jpeg',
  productSn: '6946605',
  deleteStatus: 0,
  publishStatus: 1,
  newStatus: 1,
  recommandStatus: 1,
  verifyStatus: 0,
  sort: 100,
  sale: 0,
  price: 3788.0,
  giftGrowth: 3788,
  giftPoint: 3788,
  usePointLimit: 0,
  subTitle:
    'AI智慧全面屏 6GB +64GB 亮黑色 全网通版 移动联通电信4G手机 双卡双待手机 双卡双待',
  originalPrice: 4288.0,
  stock: 1000,
  lowStock: 0,
  unit: '件',
  weight: 0.0,
  previewStatus: 1,
  serviceIds: '2,3,1',
  keywords: '',
  note: '',
  albumPics:
    'http://127.0.0.1:9090/assets/home/goodscard/img-huawei-album1.jpeg,http://127.0.0.1:9090/assets/home/goodscard/img-huawei-album2.jpeg',
  detailTitle: '',
  promotionPerLimit: 0,
  promotionType: 3,
  brandName: '华为',
  productCategoryName: '手机通讯',
};
